### ISSUE TITLE
Appraisal for this theme + Bad visibility of highlight in command palette

### ISSUE THREAD

**Issue by danieltomasz** [DiamondYuan/logseq-eink-theme#1]
I just wanted to say I really like the minimalism of this theme.
I am using in the desktop app instead of e-ink reader and I really like it!

Thank you for making it!

After I write this issue I observed that highlighting in comand palette isn't visible

![image](https://user-images.githubusercontent.com/7980381/134995197-4c0eb1ab-c542-47f6-810e-b01cc4dfb3c3.png)

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/136587563-d5261a00-660f-46f0-af40-433b550ea09e.png)
